#!/usr/bin/env python3
"""Generate all 20 MBA story JSONs for JAIN Online comic landing pages.
6 intent pages (full custom) + 14 specialization pages (per-spec customised template).
Persona = working professionals / graduates ~24-32 who want career growth without quitting
their jobs (NOT 18yo fresh-12th like BBA). Fees verified live from PMS 2026-07-07:
standard MBA Rs 2,00,000 total (Rs 50,000/sem) for the 2-yr program, reg Rs 2,500, 0% EMI
~Rs 8,333/mo; premium ACCA International Finance ~Rs 4,00,000. Brand-safe, correct English,
complete 4-panel arc, no em dashes."""
import json, pathlib
STORIES = pathlib.Path(__file__).parent / "stories"
STORIES.mkdir(exist_ok=True)

BTN = "Get my MBA plan"
def cta(pre, hl, sub="", button=BTN, burst="GO!"):
    return {"headline_pre": pre, "highlight": hl, "sub": sub, "button": button, "burst": burst}

FEE_LINE = "Rs 2,00,000 for the full 2-year MBA (Rs 50,000/semester)"
EMI_LINE = "0% interest EMI from about Rs 8,333/month, or an education loan"
REC_LINE = "UGC-entitled online MBA, NAAC A++ accredited"
STATBAR_STD = [
    {"big": "Rs 50,000", "label": "per semester"},
    {"big": "0% EMI", "label": "pay monthly"},
    {"big": "100% ONLINE", "label": "work & study"},
    {"big": "NAAC A++", "label": "accredited"},
]

# ---------------------------------------------------------------- 6 INTENT PAGES
INTENT = [
 {
  "id": "mba-course", "intent": "Generic / course overview", "program": "MBA",
  "specialization": "Online", "target_query": "mba course",
  "hero": {"eyebrow": "GROW INTO A LEADER", "headline_pre": "YOUR MBA,",
    "highlight": "ONE CLEAR PATH.", "headline_post": "", "sub": "",
    "cta1": BTN, "cta2": "Explore specialisations",
    "art_prompt": "Arjun, a 27 year old Indian man in smart business-casual, confident and hopeful, choosing a management career path on a laptop in a modern home office, aspirational mood.",
    "burst": "LET'S GO!"},
  "statbar": [{"big": "14 SPECIALISATIONS", "label": "choose your path"}, {"big": "100% ONLINE", "label": "work & study"},
    {"big": "Rs 50,000", "label": "per semester"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Arjun was good at his job, but stuck at the same level.",
     "dialogue": "I am ready for more.",
     "img_prompt": "Arjun, 27, in business-casual at his desk, capable but a little restless, looking at a laptop, modern office, thoughtful."},
    {"n": 2, "narration": "Every role he wanted asked for an MBA he did not have.",
     "dialogue": "How do I move up?",
     "img_prompt": "Arjun reading a job posting on a laptop that clearly needs a management degree, thoughtful and determined, tidy home office."},
    {"n": 3, "narration": "Then he found a clear, flexible online MBA.",
     "dialogue": "One path, without quitting my job!",
     "img_prompt": "Arjun's face lighting up with clarity at a laptop showing a clean online MBA page with specialisations, warm hopeful glow, modern home."},
    {"n": 4, "narration": "He chose a specialisation and began learning with guidance.",
     "dialogue": "My leadership journey begins!",
     "img_prompt": "Arjun confidently starting his first online MBA lesson on a laptop, notebook ready, focused and happy, warm hopeful light."}],
  "turn": {"title": "Why Start Your MBA Here", "points": [
    "Choose from 14 in-demand specialisations, from Finance and HR to Data Science and Marketing.",
    "Study 100% online with weekend live classes, so you keep earning while you learn.",
    f"Just {FEE_LINE}, with 0% interest EMI or a discount on upfront payment.",
    "Real AI tools for business, plus mentor support, from your very first semester."]},
  "proof": {"testimonials": [
    {"name": "Arjun Nair", "spec": "MBA FINANCE", "role": "Working Professional", "metric": "PROMOTED", "stat": "in 1 year",
     "quote": "I was capable but stuck. A recognised MBA gave me the credential my next role needed."},
    {"name": "Tanvi Shah", "spec": "MBA MARKETING", "role": "2nd-Year Student", "metric": "14 PATHS", "stat": "my pick",
     "quote": "Choosing my specialisation meant the degree matched the exact career I was building."},
    {"name": "Aditya Kumar", "spec": "MBA DATA SCIENCE", "role": "Career Switcher", "metric": "AI TOOLS", "stat": "from sem 1",
     "quote": "Learning real AI and analytics tools from semester one made me job-ready, not just degree-ready."},
    {"name": "Pooja Reddy", "spec": "MBA HR", "role": "Graduated", "metric": "PLACED", "stat": "recognised",
     "quote": "A recognised MBA, earned online around my job. It opened the door to a leadership role."}],
    "facts": [{"k": "Choose", "v": "14 specialisations across finance, people, data and growth"},
      {"k": "Mode", "v": "100% online, weekend live classes, learn while you work"},
      {"k": "Fee", "v": FEE_LINE}, {"k": "Recognition", "v": REC_LINE}]},
  "cta": cta("READY TO BEGIN", "YOUR MBA?"),
 },
 {
  "id": "mba-online", "intent": "Online / flexible", "program": "MBA",
  "specialization": "Online", "target_query": "online mba",
  "hero": {"eyebrow": "AN MBA THAT FITS YOUR JOB", "headline_pre": "A REAL MBA,",
    "highlight": "100% ONLINE.", "headline_post": "", "sub": "",
    "cta1": BTN, "cta2": "Explore specialisations",
    "art_prompt": "Priya, a 28 year old Indian working woman in smart-casual, smiling as she studies on a laptop in the evening at home after work, warm lamp light, balanced and aspirational.",
    "burst": "ONLINE!"},
  "statbar": [{"big": "100% ONLINE", "label": "work & study"}, {"big": "WEEKEND", "label": "live classes"},
    {"big": "0% EMI", "label": "pay monthly"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Priya wanted an MBA, but could not pause her career.",
     "dialogue": "I can't stop working.",
     "img_prompt": "Priya, 28, in office wear looking at a laptop between work tasks, ambitious but busy, modern workplace, thoughtful."},
    {"n": 2, "narration": "A full-time campus MBA meant quitting her job.",
     "dialogue": "Do I give up my salary?",
     "img_prompt": "Priya looking torn, glancing between her office ID badge and a campus MBA brochure, soft conflicted expression, tidy desk."},
    {"n": 3, "narration": "Then she found a recognised MBA she could do online.",
     "dialogue": "Study and keep my job!",
     "img_prompt": "Priya's face lighting up with relief at a laptop showing a 100% online MBA, warm glow, cosy home study corner in the evening."},
    {"n": 4, "narration": "Now she studies evenings and weekends, career intact.",
     "dialogue": "No pause, full growth.",
     "img_prompt": "Priya happily attending a weekend live online class on her laptop at home, notebook beside her, calm and confident, warm light."}],
  "turn": {"title": "Why An Online MBA Just Works", "points": [
    "Study 100% online, anytime, from your phone or laptop. No campus, no commute.",
    "Weekend live classes plus recordings, so learning fits around a full-time job.",
    "The same UGC-entitled, NAAC A++ MBA, recognised for jobs, promotions and higher studies.",
    f"Just {FEE_LINE}, with 0% interest EMI or a discount on upfront payment."]},
  "proof": {"testimonials": [
    {"name": "Priya Menon", "spec": "MBA ONLINE", "role": "Working Professional", "metric": "NO PAUSE", "stat": "kept my job",
     "quote": "I earned my MBA without a single day off work. Weekend classes and recordings made it possible."},
    {"name": "Sana Iqbal", "spec": "MBA HR", "role": "2nd-Year Student", "metric": "0% EMI", "stat": "Rs 8,333 / mo",
     "quote": "The monthly EMI fit my salary, and the schedule fit my life. It genuinely just worked."},
    {"name": "Divya Rao", "spec": "MBA MARKETING", "role": "Career Switcher", "metric": "RECOGNISED", "stat": "UGC-entitled",
     "quote": "A recognised degree earned online. My new employer accepted it without a second thought."},
    {"name": "Meena S", "spec": "MBA ONLINE", "role": "Graduated", "metric": "PROMOTED", "stat": "on my terms",
     "quote": "I studied around work and family and still graduated on time. That flexibility changed my career."}],
    "facts": [{"k": "Mode", "v": "100% online, learn anytime with weekend live classes"},
      {"k": "Fee", "v": FEE_LINE}, {"k": "EMI", "v": EMI_LINE}, {"k": "Recognition", "v": REC_LINE}]},
  "cta": cta("READY TO STUDY", "ONLINE?", burst="GO!"),
 },
 {
  "id": "mba-online-home", "intent": "Distance / from home", "program": "MBA",
  "specialization": "Online", "target_query": "distance mba",
  "hero": {"eyebrow": "NO CAMPUS NEARBY?", "headline_pre": "A REAL MBA,",
    "highlight": "100% FROM HOME.", "headline_post": "", "sub": "",
    "cta1": BTN, "cta2": "Explore specialisations",
    "art_prompt": "Meera, a 29 year old Indian woman in a modest kurta, smiling as she studies on a laptop at a tidy desk at home in a smaller town, bright daytime, warm and aspirational.",
    "burst": "FROM HOME!"},
  "statbar": [{"big": "100% ONLINE", "label": "study anywhere"}, {"big": "NO RELOCATION", "label": "stay at home"},
    {"big": "0% EMI", "label": "pay monthly"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Meera's town had no campus with a strong MBA.",
     "dialogue": "Do I have to move away?",
     "img_prompt": "Meera, 29, in a modest kurta at her window looking toward a faraway city skyline, an MBA brochure in hand, thoughtful and hopeful, small-town home."},
    {"n": 2, "narration": "Relocating for a distant campus was not an option.",
     "dialogue": "My life and work are here.",
     "img_prompt": "Meera looking torn while glancing between a suitcase and family and work responsibilities at home, warm modest room, conflicted expression."},
    {"n": 3, "narration": "Then she found a recognised MBA she could do from home.",
     "dialogue": "A campus, in my own room!",
     "img_prompt": "Meera's face lighting up with relief and excitement at a laptop showing an online MBA she can do from home, warm glow, tidy home study corner."},
    {"n": 4, "narration": "Now she studies at home, her degree on track.",
     "dialogue": "No move, a full MBA.",
     "img_prompt": "Meera happily attending an online MBA class on her laptop at home, notebook beside her, supportive family nearby, warm and encouraging."}],
  "turn": {"title": "Why A From-Home MBA Works", "points": [
    "Study 100% online from anywhere. No relocation, no hostel, no commute.",
    "The same UGC-entitled, NAAC A++ MBA as on-campus, recognised everywhere.",
    "Weekend live classes plus recordings, so learning fits around your life and work.",
    f"Just {FEE_LINE}, with 0% interest EMI or a discount on upfront payment."]},
  "proof": {"testimonials": [
    {"name": "Meera Nair", "spec": "MBA ONLINE", "role": "Working Professional", "metric": "FROM HOME", "stat": "no move",
     "quote": "There was no good campus in my town. Studying from home let me earn a real MBA without leaving."},
    {"name": "Rekha Das", "spec": "MBA FINANCE", "role": "2nd-Year Student", "metric": "0% EMI", "stat": "Rs 8,333 / mo",
     "quote": "The monthly EMI fit my budget, and I never had to move away from my family or my job."},
    {"name": "Aarti Rao", "spec": "MBA HR", "role": "Career Switcher", "metric": "RECOGNISED", "stat": "UGC-entitled",
     "quote": "A recognised degree earned from home. It was accepted without question when I switched roles."},
    {"name": "Latha S", "spec": "MBA ONLINE", "role": "Graduated", "metric": "GROWTH", "stat": "on my terms",
     "quote": "I studied around home responsibilities and still graduated on time. That flexibility meant everything."}],
    "facts": [{"k": "Mode", "v": "100% online from home, weekend live classes"},
      {"k": "No relocation", "v": "Same recognised MBA, no hostel or commute"},
      {"k": "Fee", "v": FEE_LINE}, {"k": "Recognition", "v": REC_LINE}]},
  "cta": cta("READY TO STUDY", "FROM HOME?"),
 },
 {
  "id": "mba-course-fees", "intent": "Fees / affordability", "program": "MBA",
  "specialization": "Finance", "target_query": "mba course fees",
  "hero": {"eyebrow": "THE FEE COMPARISON", "headline_pre": "A RECOGNISED MBA,",
    "highlight": "Rs 50,000/SEMESTER.", "headline_post": "", "sub": "",
    "cta1": "Get my fee + plan", "cta2": "Explore specialisations",
    "art_prompt": "Rahul, a 28 year old Indian man in smart-casual, happily surprised at a laptop showing an affordable MBA fee after comparing many options, bright hopeful mood, tidy home office.",
    "burst": "Rs 50K!"},
  "statbar": [{"big": "Rs 50,000", "label": "per semester"}, {"big": "0% EMI", "label": "pay monthly"},
    {"big": "DISCOUNT", "label": "pay upfront"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Rahul compared MBA fees, option after option.",
     "dialogue": "Why is an MBA so costly?",
     "img_prompt": "Rahul, 28, at a desk comparing several high MBA fee figures in a notebook, concerned and focused, papers around him, tidy home office."},
    {"n": 2, "narration": "Many programs ran into many lakhs of rupees.",
     "dialogue": "Is a good MBA only for the rich?",
     "img_prompt": "Rahul looking discouraged at a laptop showing an expensive MBA fee, chin in hand, soft disappointed expression, modern room."},
    {"n": 3, "narration": "Then he found a recognised MBA at Rs 50,000 a semester.",
     "dialogue": "Affordable and recognised?",
     "img_prompt": "Rahul's eyes widening with hope at a laptop showing a clear, affordable, recognised MBA fee, warm glow of relief."},
    {"n": 4, "narration": "He enrolled on a 0% EMI he could manage.",
     "dialogue": "A real MBA, no heavy debt!",
     "img_prompt": "Rahul smiling confidently holding a blank enrollment confirmation at home, calm and assured, warm hopeful light. No cash or money shown."}],
  "turn": {"title": "Why This MBA Fee Is A Steal", "points": [
    f"Just {FEE_LINE}. A recognised MBA at a fair, honest price.",
    "Pay upfront and get a discount, or split it into easy 0% interest EMI.",
    "0% interest EMI from about Rs 8,333/month, so there is no heavy lump sum.",
    "Only Rs 2,500 one-time registration. Clear fees, no hidden charges."]},
  "proof": {"testimonials": [
    {"name": "Rahul Pillai", "spec": "MBA FINANCE", "role": "Working Professional", "metric": "Rs 50K / sem", "stat": "recognised",
     "quote": "I compared everywhere. A UGC-entitled MBA at Rs 50,000 a semester was the clear, honest choice."},
    {"name": "Arjun Das", "spec": "MBA · SEM 1", "role": "1st-Year Student", "metric": "0% EMI", "stat": "Rs 8,333 / mo",
     "quote": "The 0% EMI meant no lump sum. I pay a small amount each month and my MBA keeps going."},
    {"name": "Nisha Verma", "spec": "MBA MARKETING", "role": "Career Switcher", "metric": "DISCOUNT", "stat": "paid upfront",
     "quote": "We paid upfront and got a clear discount. A recognised MBA at this price felt genuinely fair."},
    {"name": "Vikram Rao", "spec": "MBA HR", "role": "Graduated", "metric": "DEBT-LIGHT", "stat": "no burden",
     "quote": "I finished my MBA without a heavy loan. The monthly plan fit my salary perfectly."}],
    "facts": [{"k": "Fee", "v": FEE_LINE}, {"k": "Upfront", "v": "Discount on one-time full payment"},
      {"k": "EMI", "v": EMI_LINE}, {"k": "Extras", "v": "Rs 2,500 one-time registration. No hidden charges."}]},
  "cta": cta("READY TO START", "FOR Rs 50K A SEM?", button="Get my fee + plan"),
 },
 {
  "id": "mba-fees-reveal", "intent": "Fees / JAIN brand", "program": "MBA",
  "specialization": "Finance", "target_query": "jain university mba fees",
  "hero": {"eyebrow": "JAIN ONLINE MBA FEES", "headline_pre": "THE JAIN MBA FEE,",
    "highlight": "FULLY REVEALED.", "headline_post": "", "sub": "",
    "cta1": "Get my fee + plan", "cta2": "Explore specialisations",
    "art_prompt": "Sneha, a 27 year old Indian woman in smart-casual, confidently reviewing a clear, transparent MBA fee breakdown on a laptop, reassured and hopeful, tidy modern home office.",
    "burst": "CLEAR!"},
  "statbar": [{"big": "Rs 2,00,000", "label": "full MBA, 2 yrs"}, {"big": "Rs 50,000", "label": "per semester"},
    {"big": "0% EMI", "label": "pay monthly"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Sneha searched everywhere for the real JAIN MBA fee.",
     "dialogue": "What is the actual cost?",
     "img_prompt": "Sneha, 27, at a laptop searching for clear fee information, curious and focused, tidy home office."},
    {"n": 2, "narration": "Other sites showed vague numbers and hidden extras.",
     "dialogue": "Just tell me the full fee.",
     "img_prompt": "Sneha looking a little frustrated at a laptop showing unclear, incomplete fee information, modern room."},
    {"n": 3, "narration": "Then she found the full JAIN MBA fee, laid out clearly.",
     "dialogue": "Every rupee, transparent!",
     "img_prompt": "Sneha's face relaxing with relief at a laptop showing a clean, clear MBA fee breakdown, warm reassured glow."},
    {"n": 4, "narration": "She enrolled with total clarity on the cost.",
     "dialogue": "No surprises, just growth!",
     "img_prompt": "Sneha smiling confidently at her laptop after enrolling, calm and assured, warm hopeful light."}],
  "turn": {"title": "The JAIN Online MBA Fee, In Full", "points": [
    f"{FEE_LINE}. That is the complete tuition, no hidden charges.",
    "Rs 2,500 one-time registration. That is it for the essentials.",
    "Pay upfront for a discount, or choose 0% interest EMI from about Rs 8,333/month.",
    "A UGC-entitled, NAAC A++ MBA from JAIN (Deemed-to-be-University)."]},
  "proof": {"testimonials": [
    {"name": "Sneha Pillai", "spec": "MBA FINANCE", "role": "Working Professional", "metric": "Rs 2,00,000", "stat": "full MBA",
     "quote": "I just wanted the real number. JAIN showed the full MBA fee clearly, with no hidden extras."},
    {"name": "Karan Mehta", "spec": "MBA · SEM 1", "role": "1st-Year Student", "metric": "0% EMI", "stat": "Rs 8,333 / mo",
     "quote": "The monthly EMI made a JAIN MBA easy to plan. I knew my exact cost from day one."},
    {"name": "Ritu Sharma", "spec": "MBA HR", "role": "Career Switcher", "metric": "NAAC A++", "stat": "recognised",
     "quote": "A recognised JAIN MBA at a transparent fee. That trust is why I chose it over cheaper unknowns."},
    {"name": "Manoj K", "spec": "MBA MARKETING", "role": "Graduated", "metric": "CLEAR", "stat": "no surprises",
     "quote": "No hidden charges appeared, ever. The fee I saw at the start was exactly what I paid."}],
    "facts": [{"k": "Tuition", "v": FEE_LINE}, {"k": "Registration", "v": "Rs 2,500 one-time"},
      {"k": "EMI", "v": EMI_LINE}, {"k": "University", "v": "JAIN (Deemed-to-be-University), NAAC A++"}]},
  "cta": cta("READY FOR A", "JAIN MBA?", button="Get my fee + plan"),
 },
 {
  "id": "mba-admission", "intent": "Admission / how to apply", "program": "MBA",
  "specialization": "Admissions 2026", "target_query": "mba admission",
  "hero": {"eyebrow": "ADMISSIONS OPEN 2026", "headline_pre": "YOUR MBA ADMISSION,",
    "highlight": "MADE SIMPLE.", "headline_post": "", "sub": "",
    "cta1": "Start my application", "cta2": "Check eligibility",
    "art_prompt": "Karthik, a 26 year old Indian graduate in smart-casual, confidently starting an online MBA application on a laptop, relieved and hopeful, bright tidy home office.",
    "burst": "APPLY!"},
  "statbar": [{"big": "100% ONLINE", "label": "apply from home"}, {"big": "GRADUATES", "label": "any stream"},
    {"big": "NO ENTRANCE", "label": "merit based"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "A graduate with work experience, Karthik wanted an MBA.",
     "dialogue": "Where do I even start?",
     "img_prompt": "Karthik, 26, with a laptop looking unsure at a confusing admissions page, hopeful but puzzled, tidy home office."},
    {"n": 2, "narration": "The forms and steps felt scattered and confusing.",
     "dialogue": "Am I even eligible?",
     "img_prompt": "Karthik with scattered documents and notes, trying to make sense of MBA admission requirements, focused and determined."},
    {"n": 3, "narration": "Then he found one simple online admission process.",
     "dialogue": "Just a few clear steps!",
     "img_prompt": "Karthik smiling with relief at a laptop showing a clean, simple step-by-step MBA admission process, warm bright home office."},
    {"n": 4, "narration": "He applied in minutes, guided at every step.",
     "dialogue": "My application is in!",
     "img_prompt": "Karthik happily submitting his MBA application on a laptop, a small confident thumbs up, proud and relieved, warm light."}],
  "turn": {"title": "How MBA Admission Works", "points": [
    "Eligibility is simple: a bachelor's degree in any stream.",
    "The whole application is online, so you can apply from home in minutes.",
    "No entrance exam. Admission is merit based, and work experience is welcome.",
    "Upload your documents, pay the registration fee, and a counsellor guides you through."]},
  "proof": {"testimonials": [
    {"name": "Karthik Joshi", "spec": "MBA · SEM 1", "role": "Working Professional", "metric": "APPLIED", "stat": "in minutes",
     "quote": "I thought admission would be stressful. The online steps were clear and a counsellor guided me throughout."},
    {"name": "Rohan Gupta", "spec": "MBA ONLINE", "role": "1st-Year Student", "metric": "ANY STREAM", "stat": "graduate",
     "quote": "I came from an engineering background and still joined the MBA easily. No entrance exam needed."},
    {"name": "Aisha Khan", "spec": "MBA HR", "role": "Career Switcher", "metric": "FROM HOME", "stat": "fully online",
     "quote": "I applied from my phone at home. Uploading documents and paying the fee took only a few minutes."},
    {"name": "Nikhil Rao", "spec": "MBA FINANCE", "role": "2nd-Year Student", "metric": "GUIDED", "stat": "step by step",
     "quote": "Every time I had a doubt, my counsellor answered. Admission felt easy and well supported."}],
    "facts": [{"k": "Eligibility", "v": "A bachelor's degree in any stream"},
      {"k": "Process", "v": "100% online application, apply from home"},
      {"k": "Selection", "v": "Merit based, no entrance exam, work experience welcome"},
      {"k": "Support", "v": "Dedicated counsellor guides every step"}]},
  "cta": cta("READY TO APPLY", "FOR YOUR MBA?", button="Start my application"),
 },
]

# ---------------------------------------------------------------- 14 SPECIALISATION PAGES
# Compact per-spec config expanded by build_spec() into a full story.
SPECS = [
 {"id": "mba-hr", "spec": "Human Resource Management", "short": "HR", "tq": "mba in human resource management",
  "name": "Divya", "pron": "she", "poss": "her", "eyebrow": "LEAD THE PEOPLE FUNCTION", "burst": "PEOPLE!",
  "field": "handling people", "role_now": "a team coordinator",
  "learn": "talent acquisition, performance management, HR analytics and labour law",
  "skill": "People always came to me for help.", "ceiling": "How do I lead HR for real?",
  "hero_art": "Divya, a 28 year old Indian woman in business-casual, warm and confident, leading a friendly team discussion, modern office, approachable and aspirational.",
  "p1": "Divya, 28, warmly helping colleagues at work, natural people person, modern office.",
  "p2": "Divya looking thoughtful, wondering how to move from helping people to leading HR, laptop open, tidy office.",
  "p3": "Divya's face lighting up at a laptop showing an online MBA in Human Resource Management, warm hopeful glow.",
  "p4": "Divya confidently starting her first HR management lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Divya Iyer","People Manager","MY STRENGTH","now a career","I always loved supporting people. This MBA turned that into a real HR leadership path."),
   ("Kavya Menon","2nd-Year Student","HR ANALYTICS","job-ready","Learning HR analytics and modern tools made me far more than a coordinator."),
   ("Aman Gupta","Working Professional","0% EMI","kept my job","The 0% EMI and weekend classes let me grow into HR without leaving work."),
   ("Sara Thomas","Graduated","PROMOTED","to HR lead","A recognised MBA plus real people skills got me into an HR leadership role.")]},
 {"id": "mba-finance", "spec": "Finance", "short": "FINANCE", "tq": "mba in finance",
  "name": "Aditya", "pron": "he", "poss": "his", "eyebrow": "FOR FUTURE FINANCE LEADERS", "burst": "PROFIT!",
  "field": "working with numbers", "role_now": "a junior accountant",
  "learn": "financial management, investments, corporate finance and financial modelling",
  "skill": "Numbers always made sense to me.", "ceiling": "How do I lead in finance?",
  "hero_art": "Aditya, a 28 year old Indian man in business-casual, confident and happy studying rising financial charts on a laptop, modern home office, aspirational mood.",
  "p1": "Aditya, 28, happily analysing financial statements on a laptop at work, sharp and engaged, modern office.",
  "p2": "Aditya looking thoughtful, wondering how to move from accounting into finance leadership, charts on his laptop, tidy office.",
  "p3": "Aditya's face lighting up at a laptop showing an online MBA in Finance, warm hopeful glow, modern home.",
  "p4": "Aditya confidently starting his first corporate finance lesson on a laptop, notebook and calculator beside him, focused and happy, warm light.",
  "testi": [
   ("Aditya Rao","Finance Analyst","MY SKILL","now a career","I always loved finance. This MBA turned that interest into a real leadership path."),
   ("Kavya Menon","2nd-Year Student","MODELLING","job-ready","Learning financial modelling with real tools made me genuinely job-ready."),
   ("Rohit Shah","Working Professional","0% EMI","kept my job","The 0% EMI let me upskill in finance without quitting my job."),
   ("Sara Thomas","Graduated","PROMOTED","finance lead","A recognised MBA plus real finance skills got me into a finance leadership role.")]},
 {"id": "mba-healthcare", "spec": "Healthcare Management", "short": "HEALTHCARE", "tq": "mba in healthcare management",
  "name": "Ananya", "pron": "she", "poss": "her", "eyebrow": "LEAD IN HEALTHCARE", "burst": "CARE!",
  "field": "working in healthcare", "role_now": "a hospital staff member",
  "learn": "hospital operations, health systems, healthcare quality and medical administration",
  "skill": "I wanted to improve how care is run.", "ceiling": "How do I manage a hospital?",
  "hero_art": "Ananya, a 29 year old Indian woman in smart professional attire, warm and confident, managing a modern hospital corridor with staff, caring and aspirational, clean bright setting.",
  "p1": "Ananya, 29, a caring healthcare professional helping organise a busy but calm hospital ward, modern clean hospital.",
  "p2": "Ananya looking thoughtful, wondering how to move into healthcare management and leadership, clipboard in hand, hospital corridor.",
  "p3": "Ananya's face lighting up at a laptop showing an online MBA in Healthcare Management, warm hopeful glow, tidy home.",
  "p4": "Ananya confidently starting her first healthcare management lesson on a laptop at home, notebook ready, focused and happy, warm light."
  ,"testi": [
   ("Ananya Nair","Healthcare Professional","MY MISSION","now a career","I wanted to improve care delivery. This MBA gave me the tools to actually lead it."),
   ("Kavya Menon","2nd-Year Student","OPERATIONS","job-ready","Learning hospital operations and quality systems made me ready to manage, not just assist."),
   ("Imran Ali","Working Professional","0% EMI","kept my job","The 0% EMI and online classes let me study while working full shifts."),
   ("Sara Thomas","Graduated","PROMOTED","admin lead","A recognised MBA plus real healthcare skills got me into a hospital administration role.")]},
 {"id": "mba-marketing", "spec": "Marketing", "short": "MARKETING", "tq": "mba in marketing",
  "name": "Rohan", "pron": "he", "poss": "his", "eyebrow": "BUILD BRANDS THAT WIN", "burst": "BRAND!",
  "field": "understanding customers", "role_now": "a sales executive",
  "learn": "brand management, consumer behaviour, market research and sales strategy",
  "skill": "I could always read what customers want.", "ceiling": "How do I lead marketing?",
  "hero_art": "Rohan, a 28 year old Indian man in smart-casual, energetic and confident, presenting a bright brand idea on a screen, modern office, creative and aspirational.",
  "p1": "Rohan, 28, confidently pitching a marketing idea to colleagues, energetic and creative, modern office.",
  "p2": "Rohan looking thoughtful, wondering how to move from sales into marketing leadership, laptop open, tidy office.",
  "p3": "Rohan's face lighting up at a laptop showing an online MBA in Marketing, warm hopeful glow, modern home.",
  "p4": "Rohan confidently starting his first brand management lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Rohan Sen","Marketing Exec","MY INSTINCT","now a career","I always understood customers. This MBA turned that instinct into real marketing leadership."),
   ("Ananya Iyer","2nd-Year Student","STRATEGY","job-ready","Learning brand and consumer strategy made my campaigns actually work."),
   ("Dev Sharma","Working Professional","0% EMI","kept my job","The 0% EMI let me upskill in marketing without pausing my career."),
   ("Priya Menon","Graduated","PROMOTED","brand lead","A recognised MBA plus real marketing skills got me a brand leadership role.")]},
 {"id": "mba-data-science", "spec": "Data Science & Analytics", "short": "DATA SCIENCE", "tq": "mba in business analytics",
  "name": "Neha", "pron": "she", "poss": "her", "eyebrow": "TURN DATA INTO DECISIONS", "burst": "INSIGHT!",
  "field": "working with data", "role_now": "a reporting analyst",
  "learn": "business analytics, data visualisation, predictive modelling and AI for business",
  "skill": "I loved finding stories in the data.", "ceiling": "How do I drive real decisions?",
  "hero_art": "Neha, a 28 year old Indian woman in smart-casual, focused and confident, studying a clean business dashboard on a laptop, modern home office, analytical and aspirational.",
  "p1": "Neha, 28, happily exploring a data dashboard on a laptop at work, curious and analytical, modern office.",
  "p2": "Neha looking thoughtful, wondering how to move from reporting to driving business decisions, laptop with a simple chart, tidy office.",
  "p3": "Neha's face lighting up at a laptop showing an online MBA in Data Science and Analytics, warm hopeful glow.",
  "p4": "Neha confidently starting her first business analytics lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Neha Rao","Data Analyst","MY SKILL","now a career","I loved data. This MBA turned that into a real analytics and strategy career."),
   ("Kavya Menon","2nd-Year Student","AI TOOLS","job-ready","Learning predictive modelling and AI for business made me genuinely job-ready."),
   ("Arun Nair","Working Professional","0% EMI","kept my job","The 0% EMI let me move into analytics leadership without quitting my job."),
   ("Sara Thomas","Graduated","PROMOTED","analytics lead","A recognised MBA plus real data skills got me into an analytics leadership role.")]},
 {"id": "mba-logistics", "spec": "Logistics & Supply Chain Management", "short": "SUPPLY CHAIN", "tq": "mba in logistics and supply chain management",
  "name": "Vikram", "pron": "he", "poss": "his", "eyebrow": "MOVE THE WORLD FORWARD", "burst": "DELIVER!",
  "field": "keeping operations moving", "role_now": "a warehouse supervisor",
  "learn": "supply chain design, procurement, warehousing and global logistics",
  "skill": "I kept everything moving on time.", "ceiling": "How do I run the whole chain?",
  "hero_art": "Vikram, a 29 year old Indian man in smart-casual with a safety-friendly professional look, confident, overseeing an organised modern warehouse with shelves, aspirational and capable.",
  "p1": "Vikram, 29, confidently coordinating an organised modern warehouse, capable and focused, clean industrial setting.",
  "p2": "Vikram looking thoughtful, wondering how to move from supervising to leading the whole supply chain, tablet in hand, warehouse.",
  "p3": "Vikram's face lighting up at a laptop showing an online MBA in Logistics and Supply Chain Management, warm hopeful glow.",
  "p4": "Vikram confidently starting his first supply chain lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Vikram Das","Operations Lead","MY STRENGTH","now a career","I kept things moving. This MBA turned that into a real supply chain leadership path."),
   ("Kavya Menon","2nd-Year Student","GLOBAL LOGISTICS","job-ready","Learning procurement and global logistics made me ready to lead, not just supervise."),
   ("Imran Ali","Working Professional","0% EMI","kept my job","The 0% EMI let me upskill while running a busy warehouse full time."),
   ("Sara Thomas","Graduated","PROMOTED","SCM lead","A recognised MBA plus real supply chain skills got me into a management role.")]},
 {"id": "mba-operations", "spec": "Operations Management", "short": "OPERATIONS", "tq": "mba in operations management",
  "name": "Sanjay", "pron": "he", "poss": "his", "eyebrow": "MAKE EVERYTHING RUN BETTER", "burst": "OPTIMISE!",
  "field": "making processes efficient", "role_now": "a process executive",
  "learn": "operations strategy, lean and six sigma, quality and process optimisation",
  "skill": "I always spotted what to improve.", "ceiling": "How do I lead operations?",
  "hero_art": "Sanjay, a 29 year old Indian man in business-casual, confident, reviewing a clean process board in a modern facility, capable and aspirational.",
  "p1": "Sanjay, 29, confidently improving a workflow on a clean process board, sharp and focused, modern facility.",
  "p2": "Sanjay looking thoughtful, wondering how to move from executing to leading operations, laptop open, tidy office.",
  "p3": "Sanjay's face lighting up at a laptop showing an online MBA in Operations Management, warm hopeful glow.",
  "p4": "Sanjay confidently starting his first operations strategy lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Sanjay Rao","Operations Exec","MY EYE","now a career","I always spotted improvements. This MBA turned that into real operations leadership."),
   ("Kavya Menon","2nd-Year Student","LEAN & QUALITY","job-ready","Learning lean, six sigma and quality made me ready to lead operations."),
   ("Arun Nair","Working Professional","0% EMI","kept my job","The 0% EMI let me grow into operations leadership without quitting."),
   ("Sara Thomas","Graduated","PROMOTED","ops lead","A recognised MBA plus real operations skills got me a management role.")]},
 {"id": "mba-it", "spec": "Information Technology Management", "short": "IT MANAGEMENT", "tq": "mba in information technology management",
  "name": "Arun", "pron": "he", "poss": "his", "eyebrow": "LEAD TECH AND TEAMS", "burst": "SCALE!",
  "field": "working in tech", "role_now": "a software engineer",
  "learn": "IT strategy, systems, cloud, cybersecurity governance and digital transformation",
  "skill": "I could build the tech, easily.", "ceiling": "How do I lead the tech team?",
  "hero_art": "Arun, a 28 year old Indian man in smart-casual, confident, leading a tech discussion near a clean screen with abstract shapes, modern office, capable and aspirational.",
  "p1": "Arun, 28, confidently working on code and systems on a laptop, capable and focused, modern tech office.",
  "p2": "Arun looking thoughtful, wondering how to move from engineer to technology leader, laptop open, tidy office.",
  "p3": "Arun's face lighting up at a laptop showing an online MBA in Information Technology Management, warm hopeful glow.",
  "p4": "Arun confidently starting his first IT strategy lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Arun Nair","Software Engineer","MY SKILL","now a career","I could build the tech. This MBA gave me the strategy to lead the team building it."),
   ("Kavya Menon","2nd-Year Student","IT STRATEGY","job-ready","Learning IT strategy and digital transformation made me ready to manage, not just code."),
   ("Rohit Shah","Working Professional","0% EMI","kept my job","The 0% EMI let me move into tech leadership without leaving my engineering job."),
   ("Sara Thomas","Graduated","PROMOTED","tech lead","A recognised MBA plus real IT skills got me into a technology management role.")]},
 {"id": "mba-project-management", "spec": "Project Management", "short": "PROJECT MGMT", "tq": "mba in project management",
  "name": "Deepak", "pron": "he", "poss": "his", "eyebrow": "DELIVER PROJECTS THAT WIN", "burst": "DELIVER!",
  "field": "getting things delivered", "role_now": "a team lead",
  "learn": "project planning, Agile and Scrum, risk management and delivery frameworks",
  "skill": "I always got projects across the line.", "ceiling": "How do I lead big projects?",
  "hero_art": "Deepak, a 29 year old Indian man in business-casual, confident, leading a project planning session near a clean board, modern office, organised and aspirational.",
  "p1": "Deepak, 29, confidently coordinating a project with his team near a clean planning board, capable and focused, modern office.",
  "p2": "Deepak looking thoughtful, wondering how to move from team lead to leading major projects, laptop open, tidy office.",
  "p3": "Deepak's face lighting up at a laptop showing an online MBA in Project Management, warm hopeful glow.",
  "p4": "Deepak confidently starting his first project management lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Deepak Rao","Team Lead","MY STRENGTH","now a career","I always delivered. This MBA turned that into real project leadership."),
   ("Kavya Menon","2nd-Year Student","AGILE & RISK","job-ready","Learning Agile, Scrum and risk made me ready to lead complex projects."),
   ("Arun Nair","Working Professional","0% EMI","kept my job","The 0% EMI let me grow into project leadership without quitting."),
   ("Sara Thomas","Graduated","PROMOTED","project lead","A recognised MBA plus real delivery skills got me a project management role.")]},
 {"id": "mba-digital-marketing", "spec": "Digital Marketing & E-commerce", "short": "DIGITAL MKTG", "tq": "mba in digital marketing",
  "name": "Kabir", "pron": "he", "poss": "his", "eyebrow": "TURN CLICKS INTO GROWTH", "burst": "VIRAL!",
  "field": "growing brands online", "role_now": "a social media executive",
  "learn": "SEO, social media, performance ads, e-commerce and marketing analytics",
  "skill": "I could make any brand grow online.", "ceiling": "How do I lead digital growth?",
  "hero_art": "Kabir, a 27 year old Indian man in smart-casual, excited and confident, studying a rising engagement graph on a laptop, modern home office, creative and aspirational.",
  "p1": "Kabir, 27, cheerfully running online campaigns on a laptop and phone, engagement rising, creative energetic mood, modern room.",
  "p2": "Kabir looking thoughtful, wondering how to move from running posts to leading digital strategy, laptop open, tidy office.",
  "p3": "Kabir's face lighting up at a laptop showing an online MBA in Digital Marketing and E-commerce, warm hopeful glow.",
  "p4": "Kabir confidently starting his first digital marketing lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Kabir Sen","Digital Exec","MY SKILL","now a career","I was good at social media. This MBA turned that into a real digital leadership path."),
   ("Ananya Iyer","2nd-Year Student","ANALYTICS","job-ready","Learning performance ads and analytics made my campaigns genuinely deliver."),
   ("Dev Sharma","Working Professional","0% EMI","kept my job","The 0% EMI let me upskill in digital without pausing my career."),
   ("Priya Menon","Graduated","PROMOTED","growth lead","A recognised MBA plus real digital skills got me a growth leadership role.")]},
 {"id": "mba-international-business", "spec": "International Business", "short": "GLOBAL BIZ", "tq": "mba in international business",
  "name": "Isha", "pron": "she", "poss": "her", "eyebrow": "TAKE YOUR CAREER GLOBAL", "burst": "GLOBAL!",
  "field": "working across markets", "role_now": "an export coordinator",
  "learn": "global trade, cross-border strategy, export-import and international marketing",
  "skill": "I loved working across borders.", "ceiling": "How do I lead globally?",
  "hero_art": "Isha, a 28 year old Indian woman in smart professional attire, confident, working on a laptop with a subtle world-map style backdrop of soft shapes, modern office, global and aspirational.",
  "p1": "Isha, 28, confidently coordinating an international deal on a laptop and phone, capable and focused, modern office.",
  "p2": "Isha looking thoughtful, wondering how to move from coordinating to leading global business, laptop open, tidy office.",
  "p3": "Isha's face lighting up at a laptop showing an online MBA in International Business, warm hopeful glow.",
  "p4": "Isha confidently starting her first international business lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Isha Rao","Export Coordinator","MY WORLD","now a career","I loved cross-border work. This MBA turned that into a real global leadership path."),
   ("Kavya Menon","2nd-Year Student","GLOBAL TRADE","job-ready","Learning cross-border strategy made me ready to lead international business."),
   ("Rohit Shah","Working Professional","0% EMI","kept my job","The 0% EMI let me build a global career without leaving my job."),
   ("Sara Thomas","Graduated","PROMOTED","global lead","A recognised MBA plus real global skills got me an international business role.")]},
 {"id": "mba-international-finance", "spec": "International Finance", "short": "INTL FINANCE", "tq": "mba in international finance",
  "name": "Varun", "pron": "he", "poss": "his", "eyebrow": "GLOBALLY ACCREDITED FINANCE", "burst": "GLOBAL!",
  "field": "working in finance", "role_now": "a finance associate",
  "learn": "global finance, IFRS, an ACCA-aligned syllabus and international accounting",
  "skill": "I wanted a finance career without borders.", "ceiling": "How do I go global in finance?",
  "hero_art": "Varun, a 28 year old Indian man in smart professional attire, confident, studying global finance on a laptop, modern office with a subtle international feel, aspirational.",
  "p1": "Varun, 28, confidently analysing global finance figures on a laptop, sharp and engaged, modern office.",
  "p2": "Varun looking thoughtful, wondering how to build a globally recognised finance career, laptop with charts, tidy office.",
  "p3": "Varun's face lighting up at a laptop showing an online MBA in International Finance accredited by ACCA UK, warm hopeful glow.",
  "p4": "Varun confidently starting his first international finance lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Varun Rao","Finance Associate","GLOBAL","now a career","I wanted a borderless finance career. An ACCA-aligned MBA made that real."),
   ("Kavya Menon","2nd-Year Student","IFRS & ACCA","job-ready","The ACCA-aligned syllabus and IFRS made me ready for global finance roles."),
   ("Rohit Shah","Working Professional","0% EMI","kept my job","The 0% EMI let me pursue a globally accredited finance MBA without quitting."),
   ("Sara Thomas","Graduated","PROMOTED","global finance","A globally recognised MBA got me into an international finance role.")],
  "eyebrow_stat": "ACCA, UK",
  "statbar": [{"big": "ACCA, UK", "label": "global accreditation"}, {"big": "0% EMI", "label": "pay monthly"},
    {"big": "100% ONLINE", "label": "work & study"}, {"big": "NAAC A++", "label": "accredited"}],
  "learn_fee": "Rs 4,00,000 for the globally accredited 2-year MBA",
  "turn_points": [
    "Master global finance, IFRS and international accounting on an ACCA-aligned syllabus.",
    "Earn a globally accredited qualification recognised well beyond India.",
    "Rs 4,00,000 for the full globally accredited MBA, with 0% interest EMI available.",
    "A UGC-entitled, NAAC A++ online MBA, with the added weight of ACCA, UK."],
  "facts": [{"k": "Learn", "v": "Global finance, IFRS, ACCA-aligned syllabus, international accounting"},
    {"k": "Accreditation", "v": "Accredited by ACCA, UK, recognised globally"},
    {"k": "Fee", "v": "Rs 4,00,000 for the globally accredited 2-year MBA"},
    {"k": "Recognition", "v": REC_LINE}]},
 {"id": "mba-entrepreneurship", "spec": "Entrepreneurship and Leadership", "short": "STARTUP", "tq": "mba in entrepreneurship",
  "name": "Nikhil", "pron": "he", "poss": "his", "eyebrow": "BUILD YOUR OWN VENTURE", "burst": "BUILD!",
  "field": "building ideas", "role_now": "a small business owner",
  "learn": "venture creation, business planning, fundraising and leadership",
  "skill": "I had ideas, but no playbook.", "ceiling": "How do I build a real business?",
  "hero_art": "Nikhil, a 28 year old Indian man in smart-casual, energetic and confident, sketching a business idea on a clean board, modern startup space, aspirational and driven.",
  "p1": "Nikhil, 28, enthusiastically sketching a business idea on a clean whiteboard, driven and creative, modern startup space.",
  "p2": "Nikhil looking thoughtful, wondering how to turn his idea into a real, fundable business, laptop open, tidy workspace.",
  "p3": "Nikhil's face lighting up at a laptop showing an online MBA in Entrepreneurship and Leadership, warm hopeful glow.",
  "p4": "Nikhil confidently starting his first venture creation lesson on a laptop, notebook and business plan beside him, focused and happy, warm light.",
  "testi": [
   ("Nikhil Rao","Founder","MY IDEA","now a venture","I had ideas but no playbook. This MBA gave me the framework to actually build."),
   ("Kavya Menon","2nd-Year Student","FUNDRAISING","job-ready","Learning business planning and fundraising made my venture real, not just a dream."),
   ("Arun Nair","Working Professional","0% EMI","kept my job","The 0% EMI let me learn to build a business while still earning."),
   ("Sara Thomas","Graduated","LAUNCHED","my startup","A recognised MBA plus real founder skills gave me the confidence to launch.")]},
 {"id": "mba-strategy-leadership", "spec": "Strategy & Leadership", "short": "LEADERSHIP", "tq": "mba in strategy and leadership",
  "name": "Aisha", "pron": "she", "poss": "her", "eyebrow": "LEAD FROM THE FRONT", "burst": "LEAD!",
  "field": "leading people and plans", "role_now": "a senior executive",
  "learn": "corporate strategy, leadership, change management and decision-making",
  "skill": "People followed my lead naturally.", "ceiling": "How do I lead at the top?",
  "hero_art": "Aisha, a 30 year old Indian woman in smart professional attire, poised and confident, leading a strategy discussion near a clean board, modern boardroom, aspirational.",
  "p1": "Aisha, 30, confidently leading a team discussion near a clean strategy board, poised and capable, modern office.",
  "p2": "Aisha looking thoughtful, wondering how to step up from managing to leading strategy at the top, laptop open, tidy office.",
  "p3": "Aisha's face lighting up at a laptop showing an online MBA in Strategy and Leadership, warm hopeful glow.",
  "p4": "Aisha confidently starting her first strategy and leadership lesson on a laptop, notebook ready, focused and happy, warm light.",
  "testi": [
   ("Aisha Khan","Senior Executive","MY EDGE","now a career","People followed my lead. This MBA gave me the strategy to lead at the top."),
   ("Kavya Menon","2nd-Year Student","STRATEGY","job-ready","Learning corporate strategy and change management made me ready for leadership."),
   ("Rohit Shah","Working Professional","0% EMI","kept my job","The 0% EMI let me grow into senior leadership without pausing my career."),
   ("Sara Thomas","Graduated","PROMOTED","to director","A recognised MBA plus real leadership skills got me into a director-level role.")]},
]

def build_spec(c):
    name, pron, poss, spec = c["name"], c["pron"], c["poss"], c["spec"]
    short = c["short"]
    statbar = c.get("statbar", STATBAR_STD)
    learn = c["learn"]
    turn_points = c.get("turn_points", [
        f"Master the real craft: {learn}.",
        "Apply real AI tools for business from your very first semester.",
        f"{FEE_LINE}, with 0% interest EMI or a discount on upfront payment.",
        "A UGC-entitled, NAAC A++ online MBA employers and promotions recognise."])
    facts = c.get("facts", [
        {"k": "Learn", "v": learn[0].upper() + learn[1:]},
        {"k": "Fee", "v": c.get("learn_fee", FEE_LINE)},
        {"k": "EMI", "v": EMI_LINE}, {"k": "Recognition", "v": REC_LINE}])
    testimonials = [{"name": t[0], "spec": f"MBA {short}", "role": t[1], "metric": t[2], "stat": t[3], "quote": t[4]}
                    for t in c["testi"]]
    return {
      "id": c["id"], "intent": f"Specialisation / {spec}", "program": "MBA",
      "specialization": spec, "target_query": c["tq"],
      "hero": {"eyebrow": c["eyebrow"], "headline_pre": "AN MBA IN",
        "highlight": f"{spec.upper()}.", "headline_post": "", "sub": "",
        "cta1": BTN, "cta2": "Explore specialisations",
        "art_prompt": c["hero_art"], "burst": c["burst"]},
      "statbar": statbar,
      "panels": [
        {"n": 1, "narration": f"{name} was already good at {c['field']} at work.",
         "dialogue": c["skill"], "img_prompt": c["p1"]},
        {"n": 2, "narration": f"But the next step needed an MBA {pron} did not have.",
         "dialogue": c["ceiling"], "img_prompt": c["p2"]},
        {"n": 3, "narration": f"Then {pron} found an online MBA in {spec}.",
         "dialogue": "I can grow without quitting my job!", "img_prompt": c["p3"]},
        {"n": 4, "narration": f"{name} enrolled and began leading with confidence.",
         "dialogue": "From capable to qualified!", "img_prompt": c["p4"]}],
      "turn": {"title": f"Why An MBA In {spec}", "points": turn_points},
      "proof": {"testimonials": testimonials, "facts": facts},
      "cta": cta("READY TO LEAD IN", f"{spec.upper()}?"),
    }

ALL = INTENT + [build_spec(c) for c in SPECS]
for s in ALL:
    out = json.dumps(s, ensure_ascii=False, indent=2).replace("Rs ", "₹")
    (STORIES / f"{s['id']}.json").write_text(out, encoding="utf-8")
    print("wrote", s["id"], "->", s["target_query"])
print(f"\n{len(ALL)} MBA stories written ({len(INTENT)} intent + {len(SPECS)} specialisation)")
