#!/usr/bin/env python3
"""Generate the 6 remaining BBA story JSONs (demand-driven BBA set, 8 total).
Brand-safe, correct English, complete 4-panel arc (setup->conflict->turn->resolution).
Fees used only where known: BBA ₹45,000/yr (Finance/Marketing/HR), ₹50,000/yr (Digital
Marketing & Data Science + AI); reg ₹2,500 one-time + ₹3,000/yr exam. Aviation avoids a
hard fee number (not confirmed) and frames affordability via 0% EMI."""
import json, pathlib
STORIES = pathlib.Path(__file__).parent / "stories"

FACTS_ONLINE = [
    {"k": "Mode", "v": "100% online, learn anytime with weekend live classes"},
    {"k": "Fee", "v": "Rs 45,000/year (Rs 50,000 for Digital Mktg & Data Sci + AI)"},
    {"k": "EMI", "v": "0% interest monthly instalments / education loan"},
    {"k": "Recognition", "v": "UGC-entitled, NAAC A++ accredited"},
]
FACTS_FEES = [
    {"k": "Fee", "v": "Rs 45,000/year (Rs 50,000 for Digital Mktg & Data Sci + AI)"},
    {"k": "Upfront", "v": "15% discount on one-time full payment"},
    {"k": "EMI", "v": "0% interest monthly instalments / education loan"},
    {"k": "Extras", "v": "Rs 2,500 one-time registration + Rs 3,000/year exam fee"},
]

def cta(pre, hl, sub=""):
    return {"headline_pre": pre, "highlight": hl, "sub": sub,
            "button": "Get my BBA plan", "burst": "GO!"}

STORIES_DATA = [
 {
  "id": "bba-online-home", "intent": "Online / study from home", "program": "BBA",
  "specialization": "Online", "target_query": "bba online course",
  "hero": {"eyebrow": "NO COLLEGE NEARBY?", "headline_pre": "A REAL BBA,",
    "highlight": "100% FROM HOME.", "headline_post": "", "sub": "",
    "cta1": "Get my BBA plan", "cta2": "Explore electives",
    "art_prompt": "Riya, an 18 year old Indian girl in a modest salwar-kameez, smiling as she studies on a laptop at a tidy desk at home, bright hopeful daytime, warm and aspirational.",
    "burst": "FROM HOME!"},
  "statbar": [{"big": "100% ONLINE", "label": "study anywhere"},
    {"big": "NO RELOCATION", "label": "stay at home"},
    {"big": "0% EMI", "label": "pay monthly"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Riya's town had no college with a real BBA.",
     "dialogue": "Do I have to move away?",
     "img_prompt": "Riya, 18, in a modest salwar-kameez standing at her window looking toward a faraway city skyline, a BBA brochure in hand, thoughtful and hopeful, small-town Indian home."},
    {"n": 2, "narration": "Leaving home for a distant hostel felt daunting.",
     "dialogue": "So far from my family?",
     "img_prompt": "Riya looking worried while glancing between a packed bag and a family photo on the wall, warm modest room, torn expression."},
    {"n": 3, "narration": "Then she found a recognised BBA she could do online.",
     "dialogue": "College, from my own room!",
     "img_prompt": "Riya's face lighting up with relief and excitement at a laptop showing an online BBA, warm glow, tidy home study corner."},
    {"n": 4, "narration": "Now she studies at home, her degree on track.",
     "dialogue": "No move, a full degree.",
     "img_prompt": "Riya happily attending an online class on her laptop at home, notebook beside her, proud parents smiling in the background, warm and encouraging."}],
  "turn": {"title": "Why An Online BBA Just Works", "points": [
    "Study 100% online, anytime, from your phone or laptop. No campus, no commute.",
    "The same UGC-entitled, NAAC A++ BBA as on-campus, recognised everywhere.",
    "Just Rs 45,000/year with 0% interest EMI, or 15% off on upfront payment.",
    "Weekend live classes plus recordings, so learning fits around your life."]},
  "proof": {"testimonials": [
    {"name": "Riya Menon", "spec": "BBA ONLINE", "role": "1st-Year Student", "metric": "FROM HOME", "stat": "no hostel",
     "quote": "There was no good college in my town. Studying online let me earn a real BBA without leaving home."},
    {"name": "Sana Iqbal", "spec": "BBA ONLINE", "role": "2nd-Year Student", "metric": "0% EMI", "stat": "Rs 3,750 / mo",
     "quote": "The monthly EMI fit my budget, and weekend classes fit my schedule. It just worked."},
    {"name": "Divya Rao", "spec": "BBA MARKETING", "role": "Final Year", "metric": "RECOGNISED", "stat": "UGC-entitled",
     "quote": "A recognised degree earned from home. My internship team accepted it without a second thought."},
    {"name": "Meena S", "spec": "BBA ONLINE", "role": "Graduated", "metric": "PLACED", "stat": "on my terms",
     "quote": "I studied around my family responsibilities and still graduated on time. That flexibility changed everything."}],
    "facts": FACTS_ONLINE},
  "cta": cta("READY TO STUDY", "FROM HOME?"),
 },
 {
  "id": "bba-course-fees", "intent": "Fees / affordability", "program": "BBA",
  "specialization": "Finance", "target_query": "bba course fees",
  "hero": {"eyebrow": "THE FEE COMPARISON", "headline_pre": "A RECOGNISED BBA,",
    "highlight": "JUST Rs 45,000/YR.", "headline_post": "", "sub": "",
    "cta1": "Get my fee + plan", "cta2": "Explore electives",
    "art_prompt": "Sneha, an 18 year old Indian girl, happily surprised at a laptop showing an affordable BBA fee after comparing many colleges, bright hopeful mood, tidy home.",
    "burst": "Rs 45K!"},
  "statbar": [{"big": "Rs 45,000", "label": "per year"}, {"big": "0% EMI", "label": "pay monthly"},
    {"big": "15% OFF", "label": "pay upfront"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Sneha compared BBA fees, college after college.",
     "dialogue": "Why is a degree so costly?",
     "img_prompt": "Sneha, 18, at a desk comparing several high college-fee figures in a notebook, worried and overwhelmed, papers around her, modest home."},
    {"n": 2, "narration": "Most good options ran into several lakhs.",
     "dialogue": "Is a real degree only for the rich?",
     "img_prompt": "Sneha looking discouraged at a laptop showing an expensive fee, chin in hand, soft disappointed expression, modest room."},
    {"n": 3, "narration": "Then she found a recognised BBA at Rs 45,000 a year.",
     "dialogue": "Affordable and recognised?",
     "img_prompt": "Sneha's eyes widening with hope at a laptop showing a clear, affordable, recognised BBA fee, warm glow of relief."},
    {"n": 4, "narration": "She enrolled on a 0% EMI she could manage.",
     "dialogue": "A real degree, no debt!",
     "img_prompt": "Sneha smiling proudly holding a blank enrollment confirmation at home, calm and confident, warm hopeful light. No cash or money shown."}],
  "turn": {"title": "Why This BBA Fee Is A Steal", "points": [
    "Just Rs 45,000/year for Finance, Marketing or HR (Rs 50,000 for Digital Marketing & Data Science + AI).",
    "Pay the full fee upfront and get a flat 15% discount.",
    "Or split it into easy monthly EMI at 0% interest, no extra cost.",
    "Only Rs 2,500 one-time registration + Rs 3,000/year exam fee. No hidden charges."]},
  "proof": {"testimonials": [
    {"name": "Sneha Pillai", "spec": "BBA FINANCE", "role": "1st-Year Student", "metric": "Rs 45K / yr", "stat": "recognised",
     "quote": "I compared everywhere. A UGC-entitled BBA at Rs 45,000 a year was the clear, honest choice."},
    {"name": "Arjun Das", "spec": "BBA · SEM 1", "role": "1st-Year Student", "metric": "0% EMI", "stat": "Rs 3,750 / mo",
     "quote": "The 0% EMI meant no lump sum. I pay a small amount each month and my degree keeps going."},
    {"name": "Nisha Verma", "spec": "BBA DIGITAL", "role": "Final Year", "metric": "15% OFF", "stat": "Rs 42,500 / yr",
     "quote": "We paid the year upfront and got a flat 15% off. A recognised degree at this price felt unreal."},
    {"name": "Vikram Rao", "spec": "BBA MARKETING", "role": "Graduated", "metric": "DEBT-FREE", "stat": "Rs 0 loan",
     "quote": "I finished my BBA without a single education loan. The monthly plan fit my budget perfectly."}],
    "facts": FACTS_FEES},
  "cta": cta("READY TO START", "FOR Rs 45K A YEAR?"),
 },
 {
  "id": "bba-admission", "intent": "Admission / how to apply", "program": "BBA",
  "specialization": "Admissions 2026", "target_query": "bba admission",
  "hero": {"eyebrow": "ADMISSIONS OPEN 2026", "headline_pre": "YOUR BBA ADMISSION,",
    "highlight": "MADE SIMPLE.", "headline_post": "", "sub": "",
    "cta1": "Start my application", "cta2": "Check eligibility",
    "art_prompt": "Neha, an 18 year old Indian girl fresh out of class 12, confidently starting an online college application on a laptop, relieved and hopeful, bright tidy home.",
    "burst": "APPLY!"},
  "statbar": [{"big": "100% ONLINE", "label": "apply from home"}, {"big": "12th PASS", "label": "eligibility"},
    {"big": "NO ENTRANCE", "label": "merit based"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Fresh out of 12th, Neha wanted to apply for a BBA.",
     "dialogue": "Where do I even start?",
     "img_prompt": "Neha, 18, sitting with a laptop looking unsure at a confusing admissions page, question marks in her mind, modest home, hopeful but puzzled."},
    {"n": 2, "narration": "The forms and steps felt scattered and confusing.",
     "dialogue": "Am I even eligible?",
     "img_prompt": "Neha surrounded by scattered documents and notes, trying to make sense of admission requirements, slightly stressed but determined."},
    {"n": 3, "narration": "Then she found one simple online admission process.",
     "dialogue": "Just a few clear steps!",
     "img_prompt": "Neha smiling with relief at a laptop showing a clean, simple step-by-step admission process, warm bright home."},
    {"n": 4, "narration": "She applied in minutes, guided at every step.",
     "dialogue": "My application is in!",
     "img_prompt": "Neha happily submitting her application on a laptop, giving a small confident thumbs up, proud and relieved, warm hopeful light."}],
  "turn": {"title": "How BBA Admission Works", "points": [
    "Eligibility is simple: pass class 12 in any stream.",
    "The whole application is online, so you can apply from home in minutes.",
    "No entrance exam, admission is merit based on your 12th marks.",
    "Upload your documents, pay the registration fee, and a counsellor guides you through."]},
  "proof": {"testimonials": [
    {"name": "Neha Joshi", "spec": "BBA · SEM 1", "role": "1st-Year Student", "metric": "APPLIED", "stat": "in minutes",
     "quote": "I thought admission would be stressful. The online steps were clear and a counsellor guided me throughout."},
    {"name": "Rohan Gupta", "spec": "BBA ONLINE", "role": "1st-Year Student", "metric": "12th PASS", "stat": "any stream",
     "quote": "I came from a science background and still joined BBA easily. No entrance exam, just my 12th marks."},
    {"name": "Aisha Khan", "spec": "BBA HR", "role": "2nd-Year Student", "metric": "FROM HOME", "stat": "fully online",
     "quote": "I applied from my phone at home. Uploading documents and paying the fee took only a few minutes."},
    {"name": "Karan Mehta", "spec": "BBA MARKETING", "role": "Final Year", "metric": "GUIDED", "stat": "step by step",
     "quote": "Every time I had a doubt, my counsellor answered. Admission felt easy and well supported."}],
    "facts": [
    {"k": "Eligibility", "v": "Pass in class 12 (any stream)"},
    {"k": "Process", "v": "100% online application, apply from home"},
    {"k": "Selection", "v": "Merit based on 12th marks, no entrance exam"},
    {"k": "Support", "v": "Dedicated counsellor guides every step"}]},
  "cta": {"headline_pre": "READY TO APPLY", "highlight": "FOR YOUR BBA?", "sub": "",
          "button": "Start my application", "burst": "GO!"},
 },
 {
  "id": "bba-course", "intent": "Generic / course overview", "program": "BBA",
  "specialization": "Online", "target_query": "bba course",
  "hero": {"eyebrow": "START YOUR BUSINESS JOURNEY", "headline_pre": "YOUR BBA,",
    "highlight": "ONE CLEAR PATH.", "headline_post": "", "sub": "",
    "cta1": "Get my BBA plan", "cta2": "Explore electives",
    "art_prompt": "Ishaan, an 18 year old Indian boy, confident and hopeful, choosing a business path on a laptop, bright modern home, aspirational mood.",
    "burst": "LET'S GO!"},
  "statbar": [{"big": "5 ELECTIVES", "label": "choose your path"}, {"big": "100% ONLINE", "label": "study anywhere"},
    {"big": "0% EMI", "label": "from Rs 45,000"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Ishaan knew he wanted business, but not the how.",
     "dialogue": "A BBA, but which one?",
     "img_prompt": "Ishaan, 18, thoughtful in front of a laptop, imagining different business career paths, curious and a little unsure, modern home."},
    {"n": 2, "narration": "Too many colleges, electives and unclear costs.",
     "dialogue": "This is overwhelming.",
     "img_prompt": "Ishaan looking overwhelmed by many open browser options and brochures, rubbing his head, cluttered desk, modest room."},
    {"n": 3, "narration": "Then he found a clear, affordable online BBA.",
     "dialogue": "One simple path, finally!",
     "img_prompt": "Ishaan smiling with clarity at a laptop showing a clean BBA page with clear electives, warm bright home."},
    {"n": 4, "narration": "He chose an elective and started with guidance.",
     "dialogue": "My business journey begins!",
     "img_prompt": "Ishaan confidently beginning his first online lesson on a laptop, notebook ready, determined and happy, warm hopeful light."}],
  "turn": {"title": "Why Start Your BBA Here", "points": [
    "Choose from 5 industry electives: Finance, Marketing, HR, Digital Marketing, Data Science & AI.",
    "Study 100% online, anytime, from anywhere. No campus, no commute.",
    "Affordable from Rs 45,000/year with 0% interest EMI.",
    "Real AI tools, included micro-credentials and mentor support from semester 1."]},
  "proof": {"testimonials": [
    {"name": "Ishaan Nair", "spec": "BBA FINANCE", "role": "1st-Year Student", "metric": "CLEAR PATH", "stat": "guided",
     "quote": "I knew I wanted business but not the details. The clear electives and guidance made my choice easy."},
    {"name": "Tanvi Shah", "spec": "BBA ONLINE", "role": "2nd-Year Student", "metric": "5 ELECTIVES", "stat": "my pick",
     "quote": "Being able to pick my elective meant the degree actually matched the career I wanted."},
    {"name": "Aditya Kumar", "spec": "BBA DIGITAL", "role": "Final Year", "metric": "AI TOOLS", "stat": "from sem 1",
     "quote": "Learning real AI tools from the first semester made me job-ready, not just degree-ready."},
    {"name": "Pooja Reddy", "spec": "BBA MARKETING", "role": "Graduated", "metric": "PLACED", "stat": "recognised",
     "quote": "A recognised BBA, learned online at my pace. It opened the first door in my career."}],
    "facts": FACTS_ONLINE},
  "cta": cta("READY TO BEGIN", "YOUR BBA?"),
 },
 {
  "id": "bba-digital-marketing", "intent": "Specialisation / Digital Marketing", "program": "BBA",
  "specialization": "Digital Marketing", "target_query": "bba in digital marketing",
  "hero": {"eyebrow": "TURN VIRAL INTO A CAREER", "headline_pre": "A BBA IN",
    "highlight": "DIGITAL MARKETING.", "headline_post": "", "sub": "",
    "cta1": "Get my BBA plan", "cta2": "Explore electives",
    "art_prompt": "Kabir, an 18 year old Indian boy, excited at a laptop showing rising social media engagement, creative and confident, modern home, aspirational mood.",
    "burst": "VIRAL!"},
  "statbar": [{"big": "Rs 50,000", "label": "per year"}, {"big": "0% EMI", "label": "pay monthly"},
    {"big": "100% ONLINE", "label": "study anywhere"}, {"big": "NAAC A++", "label": "accredited"}],
  "panels": [
    {"n": 1, "narration": "Kabir could turn any post into a trend.",
     "dialogue": "Everyone shares my posts!",
     "img_prompt": "Kabir, 18, cheerfully creating content on a laptop and phone, social engagement rising, creative energetic mood, modern room."},
    {"n": 2, "narration": "But he had no degree to build a career on it.",
     "dialogue": "Is this just a hobby?",
     "img_prompt": "Kabir looking thoughtful, wondering how to turn his social media skill into a real career, laptop open, modest room."},
    {"n": 3, "narration": "Then he found a BBA in Digital Marketing, online.",
     "dialogue": "Turn viral into a career!",
     "img_prompt": "Kabir's face lighting up with excitement at a laptop showing a BBA in Digital Marketing, warm hopeful glow."},
    {"n": 4, "narration": "He enrolled and began learning the real craft.",
     "dialogue": "From posts to marketing!",
     "img_prompt": "Kabir confidently starting his first digital marketing lesson on a laptop, notebook ready, focused and happy, warm hopeful light."}],
  "turn": {"title": "Why A BBA In Digital Marketing", "points": [
    "Learn the real craft: SEO, social media, online ads, content and analytics.",
    "Apply real AI marketing tools from your very first semester.",
    "Rs 50,000/year with 0% interest EMI, or 15% off on upfront payment.",
    "A UGC-entitled, NAAC A++ recognised degree employers trust."]},
  "proof": {"testimonials": [
    {"name": "Kabir Sen", "spec": "BBA DIGITAL", "role": "1st-Year Student", "metric": "MY SKILL", "stat": "now a career",
     "quote": "I was already good at social media. This degree turned that skill into a real, respected career path."},
    {"name": "Ananya Iyer", "spec": "BBA DIGITAL", "role": "2nd-Year Student", "metric": "AI TOOLS", "stat": "from sem 1",
     "quote": "Learning real AI marketing tools from semester one made my campaigns actually work."},
    {"name": "Dev Sharma", "spec": "BBA DIGITAL", "role": "Final Year", "metric": "0% EMI", "stat": "easy EMI",
     "quote": "The 0% EMI let me start straight after 12th instead of waiting. Best decision I made."},
    {"name": "Priya Menon", "spec": "BBA DIGITAL", "role": "Graduated", "metric": "PLACED", "stat": "recognised",
     "quote": "A recognised BBA plus real digital skills. That mix got me hired quickly."}],
    "facts": [
    {"k": "Learn", "v": "SEO, social media, online ads, content & analytics"},
    {"k": "Fee", "v": "Rs 50,000/year, 15% off on upfront payment"},
    {"k": "EMI", "v": "0% interest monthly instalments / education loan"},
    {"k": "Recognition", "v": "UGC-entitled, NAAC A++ accredited"}]},
  "cta": cta("READY TO GO", "VIRAL?"),
 },
]

for s in STORIES_DATA:
    # normalise cta1 override for admission page
    out = json.dumps(s, ensure_ascii=False, indent=2).replace("Rs ", "₹")
    (STORIES / f"{s['id']}.json").write_text(out, encoding="utf-8")
    print("wrote", s["id"], "->", s["target_query"])
print(f"\n{len(STORIES_DATA)} stories written")
