#!/usr/bin/env python3
"""Generate M.Com (2), MA (2) and BCA (4) story JSONs for JAIN Online = 8 stories.
Fees verified live from PMS 2026-07-07: M.Com Rs 90,000 total (2yr, Rs 45,000/yr);
MA Rs 45,000 total (2yr, Rs 22,500/yr); BCA Rs 1,47,000 total (3yr, Rs 49,000/yr).
Reg Rs 2,500. Brand-safe, correct English, complete 4-panel arc, no em dashes."""
import json, pathlib
STORIES = pathlib.Path(__file__).parent / "stories"; STORIES.mkdir(exist_ok=True)

def cta(pre, hl, button, sub="", burst="GO!"):
    return {"headline_pre": pre, "highlight": hl, "sub": sub, "button": button, "burst": burst}

# ---- fee packs ----
MCOM_FEE="Rs 90,000 for the full 2-year M.Com (Rs 45,000/year)"; MCOM_EMI="0% interest EMI from about Rs 3,750/month, or an education loan"; MCOM_REC="UGC-entitled online M.Com, NAAC A++ accredited"
MA_FEE="Rs 45,000 for the full 2-year MA (Rs 22,500/year)"; MA_EMI="0% interest EMI from about Rs 1,875/month, or an education loan"; MA_REC="UGC-entitled online MA, NAAC A++ accredited"
BCA_FEE="Rs 1,47,000 for the full 3-year BCA (Rs 49,000/year)"; BCA_EMI="0% interest EMI from about Rs 4,083/month, or an education loan"; BCA_REC="UGC-entitled online BCA, NAAC A++ accredited"

MCOM_BTN="Get my M.Com plan"; MA_BTN="Get my MA plan"; BCA_BTN="Get my BCA plan"

STORIES_DATA = [
 # ============================================================ M.COM (2)
 {
  "id":"mcom-course","intent":"Generic / course overview","program":"M.Com",
  "specialization":"Online","target_query":"mcom course",
  "hero":{"eyebrow":"TAKE COMMERCE FURTHER","headline_pre":"YOUR M.COM,","highlight":"100% ONLINE.",
    "headline_post":"","sub":"","cta1":MCOM_BTN,"cta2":"Explore specialisations",
    "art_prompt":"Aditya, a 23 year old Indian commerce graduate man in smart-casual, confident and hopeful, studying advanced accounts on a laptop at home, aspirational mood.","burst":"LEVEL UP!"},
  "statbar":[{"big":"Rs 45,000","label":"per year"},{"big":"100% ONLINE","label":"work & study"},
    {"big":"0% EMI","label":"pay monthly"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Aditya finished his B.Com and wanted to go further.","dialogue":"A degree deeper in finance.",
     "img_prompt":"Aditya, 23, at a laptop reviewing advanced accounts, ambitious and focused, tidy home."},
    {"n":2,"narration":"A campus M.Com clashed with his job and plans.","dialogue":"Can I study and still work?",
     "img_prompt":"Aditya looking thoughtful, glancing between work files and a laptop, modern room."},
    {"n":3,"narration":"Then he found a recognised M.Com he could do online.","dialogue":"Advanced, and flexible!",
     "img_prompt":"Aditya's face lighting up at a laptop showing a 100% online M.Com, warm glow, cosy home study corner."},
    {"n":4,"narration":"He enrolled and deepened his expertise.","dialogue":"From graduate to expert!",
     "img_prompt":"Aditya confidently starting his first M.Com lesson on a laptop, notebook ready, focused and happy, warm light."}],
  "turn":{"title":"Why An Online M.Com Just Works","points":[
    "Go deeper: advanced accounting, finance, taxation and research, fully online.",
    "Options integrated with ACCA (UK) and CPA (US) for a global professional edge.",
    f"{MCOM_FEE}, with 0% interest EMI or a discount on upfront payment.",
    "A UGC-entitled, NAAC A++ M.Com, recognised for jobs, teaching and further study."]},
  "proof":{"testimonials":[
    {"name":"Aditya Rao","spec":"M.COM","role":"Working Professional","metric":"DEEPER","stat":"expertise",
     "quote":"My B.Com opened the door. The M.Com made me the finance expert my role needed."},
    {"name":"Kavya Menon","spec":"M.COM ACCA","role":"1st-Year Student","metric":"GLOBAL","stat":"ACCA edge",
     "quote":"The ACCA-integrated option gave my M.Com a genuine global edge."},
    {"name":"Rohit Shah","spec":"M.COM","role":"Career Switcher","metric":"0% EMI","stat":"kept my job",
     "quote":"The 0% EMI and online classes let me study while working full time."},
    {"name":"Sara Thomas","spec":"M.COM","role":"Graduated","metric":"PROMOTED","stat":"recognised",
     "quote":"A recognised M.Com plus real skills moved me into a senior finance role."}],
    "facts":[{"k":"Learn","v":"Advanced accounting, finance, taxation, research"},
      {"k":"Global","v":"ACCA (UK) and CPA (US) integrated options"},
      {"k":"Fee","v":MCOM_FEE},{"k":"Recognition","v":MCOM_REC}]},
  "cta":cta("READY TO GO","DEEPER?",MCOM_BTN),
 },
 {
  "id":"mcom-course-fees","intent":"Fees / affordability","program":"M.Com",
  "specialization":"Accounting and Finance","target_query":"mcom course fees",
  "hero":{"eyebrow":"THE FEE COMPARISON","headline_pre":"A RECOGNISED M.COM,","highlight":"JUST Rs 45,000/YR.",
    "headline_post":"","sub":"","cta1":"Get my fee + plan","cta2":"Explore specialisations",
    "art_prompt":"Priya, a 24 year old Indian commerce graduate woman in smart-casual, happily surprised at a laptop showing an affordable M.Com fee, bright hopeful mood, tidy home.","burst":"Rs 45K!"},
  "statbar":[{"big":"Rs 45,000","label":"per year"},{"big":"0% EMI","label":"pay monthly"},
    {"big":"DISCOUNT","label":"pay upfront"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Priya compared M.Com fees across many options.","dialogue":"Why is a master's so costly?",
     "img_prompt":"Priya, 24, at a desk comparing several high fee figures in a notebook, concerned and focused, tidy home."},
    {"n":2,"narration":"Most good options ran into lakhs.","dialogue":"Is further study only for the rich?",
     "img_prompt":"Priya looking discouraged at a laptop showing an expensive fee, chin in hand, soft disappointed expression, modest room."},
    {"n":3,"narration":"Then she found a recognised M.Com at Rs 45,000 a year.","dialogue":"Affordable and recognised?",
     "img_prompt":"Priya's eyes widening with hope at a laptop showing a clear, affordable, recognised M.Com fee, warm glow of relief."},
    {"n":4,"narration":"She enrolled on a 0% EMI she could manage.","dialogue":"A master's, no heavy debt!",
     "img_prompt":"Priya smiling confidently holding a blank enrollment confirmation at home, calm and assured, warm hopeful light. No cash or money shown."}],
  "turn":{"title":"Why This M.Com Fee Is A Steal","points":[
    f"Just {MCOM_FEE}. A recognised master's at a fair, honest price.",
    "Pay upfront and get a discount, or split it into easy 0% interest EMI.",
    "0% interest EMI from about Rs 3,750/month, so there is no heavy lump sum.",
    "Only Rs 2,500 one-time registration. Clear fees, no hidden charges."]},
  "proof":{"testimonials":[
    {"name":"Priya Pillai","spec":"M.COM","role":"Working Professional","metric":"Rs 45K / yr","stat":"recognised",
     "quote":"I compared everywhere. A UGC-entitled M.Com at Rs 45,000 a year was the clear, honest choice."},
    {"name":"Karan Das","spec":"M.COM · SEM 1","role":"1st-Year Student","metric":"0% EMI","stat":"Rs 3,750 / mo",
     "quote":"The 0% EMI meant no lump sum. I pay a small amount each month and my degree keeps going."},
    {"name":"Nisha Verma","spec":"M.COM ACCA","role":"Career Switcher","metric":"DISCOUNT","stat":"paid upfront",
     "quote":"We paid upfront and got a clear discount. A recognised master's at this price felt fair."},
    {"name":"Vikram Rao","spec":"M.COM","role":"Graduated","metric":"DEBT-LIGHT","stat":"no burden",
     "quote":"I finished my M.Com without a heavy loan. The monthly plan fit my budget perfectly."}],
    "facts":[{"k":"Fee","v":MCOM_FEE},{"k":"Upfront","v":"Discount on one-time full payment"},
      {"k":"EMI","v":MCOM_EMI},{"k":"Extras","v":"Rs 2,500 one-time registration. No hidden charges."}]},
  "cta":cta("READY TO START","FOR Rs 45K A YEAR?","Get my fee + plan"),
 },
 # ============================================================ MA (2)
 {
  "id":"ma-course","intent":"Generic / course overview","program":"MA",
  "specialization":"Online","target_query":"ma online course",
  "hero":{"eyebrow":"A MASTER'S, YOUR WAY","headline_pre":"YOUR MA,","highlight":"100% ONLINE.",
    "headline_post":"","sub":"","cta1":MA_BTN,"cta2":"Explore subjects",
    "art_prompt":"Meera, a 24 year old Indian graduate woman in a modest kurti, warm and hopeful, studying on a laptop at home with a few books, thoughtful aspirational mood.","burst":"ONLINE!"},
  "statbar":[{"big":"Rs 22,500","label":"per year"},{"big":"100% ONLINE","label":"study anywhere"},
    {"big":"0% EMI","label":"pay monthly"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Meera wanted a master's to teach and grow.","dialogue":"I love my subject deeply.",
     "img_prompt":"Meera, 24, happily reading and taking notes with a laptop and books at home, thoughtful and warm, tidy room."},
    {"n":2,"narration":"But a campus MA meant travel she could not manage.","dialogue":"How do I study from here?",
     "img_prompt":"Meera looking thoughtful at her window, a book in hand, modest home, hopeful but unsure."},
    {"n":3,"narration":"Then she found a recognised MA she could do online.","dialogue":"A master's, from home!",
     "img_prompt":"Meera's face lighting up with relief at a laptop showing a 100% online MA, warm glow, cosy study corner with books."},
    {"n":4,"narration":"She enrolled and dived into her subject.","dialogue":"From graduate to master!",
     "img_prompt":"Meera happily attending an online MA class on her laptop at home, notebook and books beside her, calm and content, warm light."}],
  "turn":{"title":"Why An Online MA Just Works","points":[
    "Choose your subject: English, Economics, Public Policy and more, fully online.",
    "Ideal for teaching, civil services prep, further study or a research path.",
    f"Wonderfully affordable: {MA_FEE}, with 0% interest EMI available.",
    "A UGC-entitled, NAAC A++ MA, recognised for jobs and higher study."]},
  "proof":{"testimonials":[
    {"name":"Meera Nair","spec":"MA ENGLISH","role":"1st-Year Student","metric":"FROM HOME","stat":"no travel",
     "quote":"I could finally do a master's in my subject without leaving home. It changed my plans."},
    {"name":"Sana Iqbal","spec":"MA ECONOMICS","role":"2nd-Year Student","metric":"0% EMI","stat":"Rs 1,875 / mo",
     "quote":"So affordable. The small monthly EMI made a master's genuinely within reach."},
    {"name":"Divya Rao","spec":"MA ENGLISH","role":"Career Switcher","metric":"TEACHING","stat":"my goal",
     "quote":"The MA moved me toward teaching, exactly the career I wanted."},
    {"name":"Latha S","spec":"MA","role":"Graduated","metric":"RECOGNISED","stat":"further study",
     "quote":"A recognised MA opened the door to further study and better roles."}],
    "facts":[{"k":"Subjects","v":"English, Economics, Public Policy and more"},
      {"k":"Great for","v":"Teaching, civil services prep, further study"},
      {"k":"Fee","v":MA_FEE},{"k":"Recognition","v":MA_REC}]},
  "cta":cta("READY FOR YOUR","MASTER'S?",MA_BTN),
 },
 {
  "id":"ma-english","intent":"Subject / English","program":"MA",
  "specialization":"English","target_query":"ma english distance education",
  "hero":{"eyebrow":"FOR LOVERS OF LANGUAGE","headline_pre":"AN MA IN","highlight":"ENGLISH.",
    "headline_post":"","sub":"","cta1":MA_BTN,"cta2":"Explore subjects",
    "art_prompt":"Ananya, a 24 year old Indian graduate woman in a modest kurti, warm and thoughtful, reading literature with a laptop and books at home, aspirational literary mood.","burst":"WORDS!"},
  "statbar":[{"big":"Rs 22,500","label":"per year"},{"big":"100% ONLINE","label":"study anywhere"},
    {"big":"0% EMI","label":"pay monthly"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Ananya loved literature and the craft of language.","dialogue":"Words are my world.",
     "img_prompt":"Ananya, 24, happily reading a book with a laptop nearby at home, warm thoughtful, tidy room with books."},
    {"n":2,"narration":"But turning that love into a career needed a master's.","dialogue":"How do I teach or write?",
     "img_prompt":"Ananya looking thoughtful, wondering how to build a career in English, books and a laptop around her, modest room."},
    {"n":3,"narration":"Then she found an MA in English, online.","dialogue":"My literary path starts here!",
     "img_prompt":"Ananya's face lighting up with excitement at a laptop showing an MA in English, warm hopeful glow, books nearby."},
    {"n":4,"narration":"She enrolled and immersed in literature.","dialogue":"From reader to scholar!",
     "img_prompt":"Ananya confidently starting her first MA English lesson on a laptop, open book and notebook beside her, focused and happy, warm light."}],
  "turn":{"title":"Why An MA In English","points":[
    "Study literature, linguistics, literary theory and academic writing in depth.",
    "A strong path to teaching, content, editing, civil services and research.",
    f"Wonderfully affordable: {MA_FEE}, with 0% interest EMI available.",
    "A UGC-entitled, NAAC A++ MA in English, recognised for jobs and further study."]},
  "proof":{"testimonials":[
    {"name":"Ananya Iyer","spec":"MA ENGLISH","role":"1st-Year Student","metric":"MY PASSION","stat":"now a path",
     "quote":"I loved literature. This MA turned that love into a real path toward teaching."},
    {"name":"Kavya Menon","spec":"MA ENGLISH","role":"2nd-Year Student","metric":"FROM HOME","stat":"online",
     "quote":"I studied literature deeply from home, around my other responsibilities."},
    {"name":"Arun Nair","spec":"MA ENGLISH","role":"Career Switcher","metric":"0% EMI","stat":"Rs 1,875 / mo",
     "quote":"So affordable. The small monthly EMI made a master's in English easy to start."},
    {"name":"Sara Thomas","spec":"MA ENGLISH","role":"Graduated","metric":"TEACHING","stat":"recognised",
     "quote":"A recognised MA in English got me into the teaching role I always wanted."}],
    "facts":[{"k":"Learn","v":"Literature, linguistics, literary theory, academic writing"},
      {"k":"Great for","v":"Teaching, content, editing, civil services, research"},
      {"k":"Fee","v":MA_FEE},{"k":"Recognition","v":MA_REC}]},
  "cta":cta("READY FOR A LIFE","IN LETTERS?",MA_BTN),
 },
 # ============================================================ BCA (4)
 {
  "id":"bca-course","intent":"Generic / course overview","program":"BCA",
  "specialization":"Online","target_query":"bca course",
  "hero":{"eyebrow":"START IN TECH, EARLY","headline_pre":"YOUR BCA,","highlight":"ONE CLEAR PATH.",
    "headline_post":"","sub":"","cta1":BCA_BTN,"cta2":"Explore specialisations",
    "art_prompt":"Arjun, an 18 year old Indian student in a casual collared shirt, confident and hopeful, exploring coding on a laptop at home, bright aspirational mood.","burst":"LET'S GO!"},
  "statbar":[{"big":"SPECIALISATIONS","label":"choose your path"},{"big":"100% ONLINE","label":"study anywhere"},
    {"big":"Rs 49,000","label":"per year"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Fresh out of 12th, Arjun loved computers.","dialogue":"I want to build tech.",
     "img_prompt":"Arjun, 18, happily exploring simple code shapes on a laptop at home, curious and driven, tidy room."},
    {"n":2,"narration":"But too many options left him unsure where to start.","dialogue":"Which path is right?",
     "img_prompt":"Arjun looking a little overwhelmed by many browser options on a laptop, rubbing his head, modest room."},
    {"n":3,"narration":"Then he found a clear, recognised online BCA.","dialogue":"One solid path, finally!",
     "img_prompt":"Arjun smiling with clarity at a laptop showing a clean BCA page with specialisations, warm bright home."},
    {"n":4,"narration":"He picked a specialisation and started with guidance.","dialogue":"My tech journey begins!",
     "img_prompt":"Arjun confidently starting his first BCA lesson on a laptop, notebook ready, focused and happy, warm light."}],
  "turn":{"title":"Why Start Your BCA Here","points":[
    "Choose in-demand tech tracks: Data Science, Cloud, AI, Cyber Security and more.",
    "Study 100% online, anytime, from anywhere. No campus, no commute.",
    f"Just {BCA_FEE}, with 0% interest EMI or a discount on upfront payment.",
    "Real, hands-on coding, included micro-credentials and mentor support from semester 1."]},
  "proof":{"testimonials":[
    {"name":"Arjun Nair","spec":"BCA DATA SCIENCE","role":"1st-Year Student","metric":"CLEAR PATH","stat":"guided",
     "quote":"I loved computers but did not know where to start. The clear tracks made my choice easy."},
    {"name":"Tanvi Shah","spec":"BCA CLOUD","role":"2nd-Year Student","metric":"MY PICK","stat":"my path",
     "quote":"Picking my specialisation meant the degree matched the tech job I wanted."},
    {"name":"Aditya Kumar","spec":"BCA AI","role":"Final Year","metric":"HANDS-ON","stat":"from sem 1",
     "quote":"Real projects from semester one made me genuinely job-ready, not just certified."},
    {"name":"Pooja Reddy","spec":"BCA DATA SCIENCE","role":"Graduated","metric":"PLACED","stat":"recognised",
     "quote":"A recognised BCA, learned online at my pace. It opened my first tech role."}],
    "facts":[{"k":"Choose","v":"Data Science, Cloud, AI, Cyber Security and more"},
      {"k":"Mode","v":"100% online, learn anytime with weekend live classes"},
      {"k":"Fee","v":BCA_FEE},{"k":"Recognition","v":BCA_REC}]},
  "cta":cta("READY TO BEGIN","YOUR BCA?",BCA_BTN),
 },
 {
  "id":"bca-online","intent":"Online / from home","program":"BCA",
  "specialization":"Online","target_query":"online bca course",
  "hero":{"eyebrow":"A REAL BCA, FROM HOME","headline_pre":"A REAL BCA,","highlight":"100% FROM HOME.",
    "headline_post":"","sub":"","cta1":BCA_BTN,"cta2":"Explore specialisations",
    "art_prompt":"Diya, an 18 year old Indian girl in a modest kurti, smiling as she studies coding on a laptop at a tidy desk at home, bright hopeful daytime, warm and aspirational.","burst":"FROM HOME!"},
  "statbar":[{"big":"100% ONLINE","label":"study anywhere"},{"big":"NO RELOCATION","label":"stay at home"},
    {"big":"0% EMI","label":"pay monthly"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Diya's town had no strong computer-applications college.","dialogue":"Do I have to move away?",
     "img_prompt":"Diya, 18, in a modest kurti at her window looking toward a faraway city, a brochure in hand, thoughtful hopeful, small-town home."},
    {"n":2,"narration":"Leaving home for a distant campus felt daunting.","dialogue":"So far from my family?",
     "img_prompt":"Diya looking torn while glancing between a packed bag and a family photo on the wall, warm modest room."},
    {"n":3,"narration":"Then she found a recognised BCA she could do online.","dialogue":"Tech college, from home!",
     "img_prompt":"Diya's face lighting up with relief at a laptop showing an online BCA, warm glow, tidy home study corner."},
    {"n":4,"narration":"Now she studies at home, her degree on track.","dialogue":"No move, a full degree.",
     "img_prompt":"Diya happily attending an online BCA class on her laptop at home, notebook beside her, proud family in the background, warm encouraging light."}],
  "turn":{"title":"Why An Online BCA Just Works","points":[
    "Study 100% online from anywhere. No relocation, no hostel, no commute.",
    "The same UGC-entitled, NAAC A++ BCA as on-campus, recognised everywhere.",
    f"Just {BCA_FEE}, with 0% interest EMI or a discount on upfront payment.",
    "Weekend live classes plus recordings, so learning fits around your life."]},
  "proof":{"testimonials":[
    {"name":"Diya Menon","spec":"BCA ONLINE","role":"1st-Year Student","metric":"FROM HOME","stat":"no hostel",
     "quote":"There was no good tech college in my town. Studying online let me earn a real BCA without leaving home."},
    {"name":"Sana Iqbal","spec":"BCA CLOUD","role":"2nd-Year Student","metric":"0% EMI","stat":"Rs 4,083 / mo",
     "quote":"The monthly EMI fit my budget, and weekend classes fit my schedule. It just worked."},
    {"name":"Divya Rao","spec":"BCA DATA SCIENCE","role":"Final Year","metric":"RECOGNISED","stat":"UGC-entitled",
     "quote":"A recognised degree earned from home. My internship team accepted it without a second thought."},
    {"name":"Meena S","spec":"BCA ONLINE","role":"Graduated","metric":"ON TIME","stat":"on my terms",
     "quote":"I studied around family responsibilities and still graduated on time. That flexibility changed everything."}],
    "facts":[{"k":"Mode","v":"100% online from home, weekend live classes"},
      {"k":"No relocation","v":"Same recognised BCA, no hostel or commute"},
      {"k":"Fee","v":BCA_FEE},{"k":"Recognition","v":BCA_REC}]},
  "cta":cta("READY TO STUDY","FROM HOME?",BCA_BTN),
 },
 {
  "id":"bca-course-fees","intent":"Fees / affordability","program":"BCA",
  "specialization":"Data Science","target_query":"bca course fees",
  "hero":{"eyebrow":"THE FEE COMPARISON","headline_pre":"A RECOGNISED BCA,","highlight":"JUST Rs 49,000/YR.",
    "headline_post":"","sub":"","cta1":"Get my fee + plan","cta2":"Explore specialisations",
    "art_prompt":"Rohan, an 18 year old Indian student, happily surprised at a laptop showing an affordable BCA fee after comparing colleges, bright hopeful mood, tidy home.","burst":"Rs 49K!"},
  "statbar":[{"big":"Rs 49,000","label":"per year"},{"big":"0% EMI","label":"pay monthly"},
    {"big":"DISCOUNT","label":"pay upfront"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Rohan compared BCA fees, college after college.","dialogue":"Why is tech study so costly?",
     "img_prompt":"Rohan, 18, at a desk comparing several high college-fee figures in a notebook, concerned, papers around him, modest home."},
    {"n":2,"narration":"Most good options ran into several lakhs.","dialogue":"Is a real degree only for the rich?",
     "img_prompt":"Rohan looking discouraged at a laptop showing an expensive fee, chin in hand, soft disappointed expression, modest room."},
    {"n":3,"narration":"Then he found a recognised BCA at Rs 49,000 a year.","dialogue":"Affordable and recognised?",
     "img_prompt":"Rohan's eyes widening with hope at a laptop showing a clear, affordable, recognised BCA fee, warm glow of relief."},
    {"n":4,"narration":"He enrolled on a 0% EMI he could manage.","dialogue":"A real degree, no debt!",
     "img_prompt":"Rohan smiling proudly holding a blank enrollment confirmation at home, calm and confident, warm hopeful light. No cash or money shown."}],
  "turn":{"title":"Why This BCA Fee Is A Steal","points":[
    f"Just {BCA_FEE}. A recognised tech degree at a fair, honest price.",
    "Pay the full year upfront and get a discount, or split it into easy 0% interest EMI.",
    "0% interest EMI from about Rs 4,083/month, no extra cost.",
    "Only Rs 2,500 one-time registration. Clear fees, no hidden charges."]},
  "proof":{"testimonials":[
    {"name":"Rohan Pillai","spec":"BCA DATA SCIENCE","role":"1st-Year Student","metric":"Rs 49K / yr","stat":"recognised",
     "quote":"I compared everywhere. A UGC-entitled BCA at Rs 49,000 a year was the clear, honest choice."},
    {"name":"Arjun Das","spec":"BCA · SEM 1","role":"1st-Year Student","metric":"0% EMI","stat":"Rs 4,083 / mo",
     "quote":"The 0% EMI meant no lump sum. I pay a small amount each month and my degree keeps going."},
    {"name":"Nisha Verma","spec":"BCA CLOUD","role":"Final Year","metric":"DISCOUNT","stat":"paid upfront",
     "quote":"We paid the year upfront and got a clear discount. A recognised degree at this price felt unreal."},
    {"name":"Vikram Rao","spec":"BCA AI","role":"Graduated","metric":"DEBT-FREE","stat":"Rs 0 loan",
     "quote":"I finished my BCA without a single education loan. The monthly plan fit my budget perfectly."}],
    "facts":[{"k":"Fee","v":BCA_FEE},{"k":"Upfront","v":"Discount on one-time full payment"},
      {"k":"EMI","v":BCA_EMI},{"k":"Extras","v":"Rs 2,500 one-time registration. No hidden charges."}]},
  "cta":cta("READY TO START","FOR Rs 49K A YEAR?","Get my fee + plan"),
 },
 {
  "id":"bca-data-science","intent":"Specialisation / Data Science","program":"BCA",
  "specialization":"Data Science","target_query":"bca in data science",
  "hero":{"eyebrow":"TURN DATA INTO A CAREER","headline_pre":"A BCA IN","highlight":"DATA SCIENCE.",
    "headline_post":"","sub":"","cta1":BCA_BTN,"cta2":"Explore specialisations",
    "art_prompt":"Neha, an 18 year old Indian student, focused and confident, studying a clean data chart on a laptop at home, analytical and aspirational mood.","burst":"INSIGHT!"},
  "statbar":[{"big":"Rs 49,000","label":"per year"},{"big":"0% EMI","label":"pay monthly"},
    {"big":"100% ONLINE","label":"study anywhere"},{"big":"NAAC A++","label":"accredited"}],
  "panels":[
    {"n":1,"narration":"Neha loved finding patterns and solving puzzles.","dialogue":"Data is where I shine.",
     "img_prompt":"Neha, 18, happily exploring a simple data chart on a laptop at home, curious and analytical, tidy room."},
    {"n":2,"narration":"But a data career needed real, early training.","dialogue":"How do I start young?",
     "img_prompt":"Neha looking thoughtful, wondering how to build a data science career, a laptop with a simple chart open, modest room."},
    {"n":3,"narration":"Then she found a BCA in Data Science, online.","dialogue":"My data career starts here!",
     "img_prompt":"Neha's face lighting up with excitement at a laptop showing a BCA in Data Science, warm hopeful glow."},
    {"n":4,"narration":"She enrolled and began mastering the craft.","dialogue":"From curious to qualified!",
     "img_prompt":"Neha confidently starting her first data science lesson on a laptop, notebook ready, focused and happy, warm light."}],
  "turn":{"title":"Why A BCA In Data Science","points":[
    "Master the real craft early: Python, data visualisation, statistics and AI basics.",
    "Apply real, hands-on projects and included micro-credentials from semester one.",
    f"{BCA_FEE}, with 0% interest EMI or a discount on upfront payment.",
    "A UGC-entitled, NAAC A++ BCA that tech employers recognise."]},
  "proof":{"testimonials":[
    {"name":"Neha Rao","spec":"BCA DATA SCIENCE","role":"1st-Year Student","metric":"MY SKILL","stat":"now a career",
     "quote":"I loved data. This BCA turned that into a real, early start in a data career."},
    {"name":"Kavya Menon","spec":"BCA DATA SCIENCE","role":"2nd-Year Student","metric":"HANDS-ON","stat":"from sem 1",
     "quote":"Real projects from semester one made me genuinely job-ready, right after 12th."},
    {"name":"Aman Gupta","spec":"BCA DATA SCIENCE","role":"Final Year","metric":"0% EMI","stat":"Rs 4,083 / mo",
     "quote":"The 0% EMI let me start straight after 12th instead of waiting years to save up."},
    {"name":"Sara Thomas","spec":"BCA DATA SCIENCE","role":"Graduated","metric":"PLACED","stat":"recognised",
     "quote":"A recognised BCA plus real data skills got me hired into a data role quickly."}],
    "facts":[{"k":"Learn","v":"Python, data visualisation, statistics, AI basics"},
      {"k":"Fee","v":BCA_FEE},{"k":"EMI","v":BCA_EMI},{"k":"Recognition","v":BCA_REC}]},
  "cta":cta("READY FOR A","DATA CAREER?",BCA_BTN),
 },
]

for s in STORIES_DATA:
    out = json.dumps(s, ensure_ascii=False, indent=2).replace("Rs ", "₹")
    (STORIES / f"{s['id']}.json").write_text(out, encoding="utf-8")
    print("wrote", s["id"], "->", s["target_query"])
print(f"\n{len(STORIES_DATA)} stories written (M.Com 2 + MA 2 + BCA 4)")
